### ISSUE TITLE
Service commands should also work on individual services

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Tooling#38]
Currently, `deploy`, `undeploy`, and `status` work on all defined services.  Enhance the commands so that can can optionally work on an individual service.

```
$ st status
foo-config online
foo-dash online
foo-redis online
foo-mssql online
foo-zip online
foo-eureka online

$ st status foo-config
foo-config online
```

**Comment by ccheetham** [comment]
Other than `status`, this will probably not be feasible.  A deployment target, e.g. CloudFoundry, you can't undeploy a service if an app is bound to it.

Perhaps keep `undeploy` as is and add individual service support for `deploy` and `status`.

**Comment by jkonicki** [comment]
Closing as invalid
