### ISSUE TITLE
Unable to install SteelToe .NET core linux microservice template

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Tooling#91]
Hi,
I tried to install SteelToe Linux microservice, But the installation failed. attached is the issue log.
[dd_VSIXInstaller_20191201100527_1adc.log](https://github.com/SteeltoeOSS/Tooling/files/3907820/dd_VSIXInstaller_20191201100527_1adc.log)

synopsis of the log 

>  Beginning to install extension to Microsoft Visual Studio Community 2019...
> 12/1/2019 10:05:40 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
> -Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1 (Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1)

**Comment by ddieruf** [comment]
We have moved the project to [steeltoe incubator](https://github.com/steeltoeoss-incubator/vs-extensions), updated to the latest Steeltoe & .NET versions, and removed the blocking dependency. It was not needed.
