### ISSUE TITLE
Unable to install SteelToe .NEt core windows microservice

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Tooling#93]
When installing this template in for Visual studio 2019 we are getting an error as per attached error log 
[dd_VSIXInstaller_20191201105157_16a8.log](https://github.com/SteeltoeOSS/Tooling/files/3907845/dd_VSIXInstaller_20191201105157_16a8.log)

**Comment by ddieruf** [comment]
I moved the project to steeltoe incubator, updated to the latest everything, and removed the VSIX dependency that was blocking install as it was unneeded.
